{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      {{- if .Values.gateway.hostname }}
      hostname: {{ .Values.gateway.hostname | quote }}
      {{- end }}
    {{- if .Values.gateway.tls.enabled }}
    - name: https
      protocol: HTTPS
      port: 443
      hostname: {{ .Values.gateway.hostname | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.gateway.tls.secretName }}
    {{- end }}
{{- end }}
