apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.fullname" . }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"
    helm.sh/resource-policy: keep
type: Opaque
data:
  POSTGRES_USER: {{ .Values.credentials.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.credentials.postgresPassword | b64enc | quote }}
  POSTGRES_DB: {{ .Values.credentials.postgresDb | b64enc | quote }}
