{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "backend.fullname" . }}-db
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.storeName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "backend.fullname" . }}-db
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_USER
      remoteRef:
        key: {{ .Values.externalSecrets.keys.databaseUser }}
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.keys.databasePassword }}
{{- end }}
